/* ----------------------------------------------------------------------------

    MIT License

    Copyright (c) 2024 MW

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.

---------------------------------------------------------------------------- */

import { Common } from "../standard/common.slint";


export component RButton inherits Rectangle {
    in-out property <color> back-color: Common.back-color;
    in-out property <color> click-color: Common.click-color;
    in-out property <color> hover-color: Common.hover-color;
    in-out property <color> text-color: Common.text-color;
    in-out property <color> text-click-color: Common.text-click-color;
    
    callback clicked <=> touch.clicked;

    width: Common.button-width;
    height: Common.button-height;
    preferred-width: Common.button-width;
    preferred-height: Common.button-height;

    Rectangle {
        width: Common.button-width - Common.button-padding-horizontal * 2;
        height: Common.button-height - Common.button-padding-vertical * 2;
        preferred-width: Common.button-width - Common.button-padding-horizontal * 2;
        preferred-height: Common.button-height - Common.button-padding-vertical * 2;
    
        background: touch.pressed ? parent.click-color : touch.has-hover ? parent.hover-color :  parent.back-color;
        border-color: Common.border-color;
        border-radius: root.height / Common.button-corner-radius;
        border-width: Common.button-border-size;
    }

    padding-left: Common.button-padding-horizontal;
    padding-right: Common.button-padding-horizontal;
    padding-top: Common.button-padding-vertical;
    padding-bottom: Common.button-padding-vertical;
    
    touch := TouchArea { }
    
    in-out property text <=> label.text;
    
    label := Text {
        color: touch.pressed ? parent.text-click-color : parent.text-color;
        font-size: Common.font-size;
        text: "Button";
    }
}

export component RBlueButton inherits RButton {
    back-color: royalblue;
    text-color: white;
}

export component RRedButton inherits RButton {
    back-color: crimson;
    text-color: white;
}

export component RWhiteButton inherits RButton {
    back-color: white;
    text-color: black;
}