export global Common {
    out property <color> window-back-color: navajowhite;
    
    // Control colours...
    out property <color> border-color: slategray;
    out property <color> back-color: dodgerblue;
    out property <color> click-color: steelblue;
    out property <color> hover-color: cornflowerblue;
    out property <color> text-color: white;
    out property <color> text-click-color: antiquewhite;
    
    out property <color> bar-back-color: gray;
    out property <color> bar-border-color: slategray;

    // Sizing...
    out property <length> window-width: 600px;
    out property <length> window-height: 600px;
    out property <length> window-min-width: 350px;
    out property <length> window-min-height: 250px;
    
    out property <length> bar-border-size: 1px;
    out property <int> bar-corner-radius: 12;
    out property <length> bar-padding: 4px;

    out property <length> button-border-size: 1px;
    out property <int> button-corner-radius: 8;
    out property <length> button-width: 165px;
    out property <length> button-height: 36px;
    out property <length> button-padding-horizontal: 4px;
    out property <length> button-padding-vertical: 2px;

    out property <length> edit-width: 200px;
    out property <length> edit-height: 32px;
    out property <length> edit-padding-horizontal: 5px;
    out property <length> edit-padding-vertical: 2px;

    // Fonts...
    out property <length> font-size: 15px;
}
